backend: hmp

runtime:
  use_gpu: true
  visualize: false
  mano_model_path: ./mano_data
  hmp_assets_root: ./_DATA/hmp_model
  hmp_model_config: ./hmp_clean/hmp_model_config.yaml

refinement:
  overlap: 48
  pose:
    iters: 120
    lr: 0.03
    weights:
      rot: 0.01
      pos: 0.01
      root: 1
      latent: 0.01
  beta:
    optimize: true
    iters: 120
    lr: 0.03
    weights:
      joint: 1
      prior: 0.01
