from __future__ import annotations

from typing import List

from .models import ControlSpec, ModeSpec
from .settings import PRIMARY_FAMILIES


def visualization_modes() -> List[ModeSpec]:
    camera_controls = [
        ControlSpec(id="fov_deg", label="Field of View", type="number", default=60.0, min=10, max=160, step=1),
        ControlSpec(id="aspect", label="Aspect Ratio", type="number", default=16 / 9, min=0.5, max=3, step=0.01),
        ControlSpec(id="frustum_scale", label="Frustum Scale", type="number", default=0.5, min=0.01, max=5, step=0.01),
        ControlSpec(id="trajectory_stride", label="Trajectory Stride", type="number", default=5, min=1, max=100, step=1),
        ControlSpec(id="center_radius", label="Center Radius", type="number", default=0.02, min=0.001, max=2, step=0.001),
        ControlSpec(id="center_to_first_frame", label="Center to First Frame", type="boolean", default=True),
        ControlSpec(id="translation_scale", label="Translation Scale", type="number", default=1.0, min=0.001, max=100, step=0.01),
        ControlSpec(id="invert_cam_t", label="Invert Camera Translation", type="boolean", default=True),
    ]
    return [
        ModeSpec(
            id="free_view",
            label="Free View",
            tab="visualization",
            script_name="3D Visualization /Free.py",
            purpose="Free-view animated hand visualization for model meshes or MediaPipe joints.",
            required_inputs=["One primary source"],
            optional_arguments=["None"],
            expected_outputs=["Animated 3D hand scene"],
            ui_appearance="Single selectable visualization mode with shared playback controls.",
            supported_families=list(PRIMARY_FAMILIES),
        ),
        ModeSpec(
            id="wrist_grounded",
            label="Wrist Grounded",
            tab="visualization",
            script_name="3D Visualization /Wrist Grounding.py",
            purpose="Wrist-centered animated visualization for model meshes or MediaPipe joints.",
            required_inputs=["One primary source"],
            optional_arguments=["wrist_joint_idx"],
            expected_outputs=["Wrist-grounded 3D animation"],
            ui_appearance="Visualization mode with wrist-joint numeric control.",
            supported_families=list(PRIMARY_FAMILIES),
            controls=[
                ControlSpec(id="wrist_joint_idx", label="Wrist Joint Index", type="number", default=0, min=0, max=31, step=1),
            ],
        ),
        ModeSpec(
            id="camera_trajectories",
            label="Camera Trajectories",
            tab="visualization",
            script_name="3D Visualization /Camera.py",
            purpose="Model and optional ViPE camera/frustum trajectory visualization with shared camera display settings.",
            required_inputs=["One camera-capable primary source", "Optional ViPE overlay"],
            optional_arguments=["fov_deg", "aspect", "frustum_scale", "trajectory_stride", "center_radius", "center_to_first_frame", "translation_scale", "invert_cam_t"],
            expected_outputs=["3D trajectory lines", "Camera frusta", "Optional ViPE overlay"],
            ui_appearance="Mode panel with shared camera display controls and overlay toggles.",
            supported_families=["wilor", "wilor_finetune", "hamba", "dynhamr", "stride"],
            controls=camera_controls,
        ),
        ModeSpec(
            id="bounding_boxes",
            label="Bounding Boxes",
            tab="visualization",
            script_name="3D Visualization /Bounding Boxes.py",
            purpose="Bounding-box track visualization for model sources with bbox metadata.",
            required_inputs=["One bbox-capable model source"],
            optional_arguments=["box_stride", "center_radius", "line_width", "time_spacing"],
            expected_outputs=["3D bbox tracks", "Center-point tracks"],
            ui_appearance="Mode panel with track spacing and radius controls.",
            supported_families=["wilor", "wilor_finetune", "hamba", "dynhamr", "stride"],
            controls=[
                ControlSpec(id="box_stride", label="Box Stride", type="number", default=5, min=1, max=100, step=1),
                ControlSpec(id="center_radius", label="Center Radius", type="number", default=4.0, min=0.1, max=20.0, step=0.1),
                ControlSpec(id="line_width", label="Line Width", type="number", default=2.0, min=0.1, max=10.0, step=0.1),
                ControlSpec(id="time_spacing", label="Time Spacing", type="number", default=10.0, min=0.1, max=100.0, step=0.1),
            ],
        ),
        ModeSpec(
            id="camera_space_meshes",
            label="Camera-Space Meshes",
            tab="visualization",
            script_name="3D Visualization /visualize_camera_space.py",
            purpose="Camera-space mesh animation for compatible model sources.",
            required_inputs=["One compatible model source"],
            optional_arguments=["wrist_joint_idx"],
            expected_outputs=["Animated camera-space mesh scene"],
            ui_appearance="Mode panel with wrist-joint numeric control.",
            supported_families=["wilor", "wilor_finetune", "hamba", "dynhamr", "stride"],
            controls=[
                ControlSpec(id="wrist_joint_idx", label="Wrist Joint Index", type="number", default=0, min=0, max=31, step=1),
            ],
        ),
        ModeSpec(
            id="beta_average_meshes",
            label="Beta Average Meshes",
            tab="visualization",
            script_name="3D Visualization /beta average.py",
            purpose="Reconstructed animation using one sequence-average beta vector and original per-frame poses.",
            required_inputs=["One beta-compatible model source"],
            optional_arguments=["wrist_ground", "wrist_joint_idx"],
            expected_outputs=["Animated averaged-beta mesh scene"],
            ui_appearance="Mode panel with wrist-grounding toggle and wrist index control.",
            supported_families=["wilor", "wilor_finetune", "dynhamr", "stride"],
            controls=[
                ControlSpec(id="wrist_ground", label="Wrist Ground", type="boolean", default=False),
                ControlSpec(id="wrist_joint_idx", label="Wrist Joint Index", type="number", default=0, min=0, max=31, step=1),
            ],
        ),
        ModeSpec(
            id="mano_debug",
            label="MANO Debug",
            tab="visualization",
            script_name="3D Visualization /MANO.py",
            purpose="Advanced MANO topology/debug viewer.",
            required_inputs=["MANO model asset"],
            optional_arguments=["None"],
            expected_outputs=["Static labeled MANO mesh"],
            ui_appearance="Advanced-only mode outside the normal clip tree.",
            supported_families=[],
        ),
    ]


def analysis_modes() -> List[ModeSpec]:
    base_controls = [
        ControlSpec(
            id="hand",
            label="Hand",
            type="select",
            default="auto",
            options=[
                {"label": "Auto", "value": "auto"},
                {"label": "Right", "value": "right"},
                {"label": "Left", "value": "left"},
                {"label": "Unknown", "value": "unknown"},
            ],
        ),
        ControlSpec(id="fps", label="FPS", type="number", default=30.0, min=1.0, max=240.0, step=0.01),
        ControlSpec(id="wrist_joint_idx", label="Wrist Joint Index", type="number", default=0, min=0, max=31, step=1),
    ]
    return [
        ModeSpec(
            id="centroid_compare",
            label="Centroid Compare",
            tab="analysis",
            script_name="Frequency Analysis/Compare.py",
            purpose="Centroid-based tremor frequency analysis for one or more selected sources.",
            required_inputs=["One or more selected sources"],
            optional_arguments=["hand", "fps", "wrist_joint_idx"],
            expected_outputs=["Magnitude trace", "PSD", "Dominant frequency", "Peak ratio", "Temporal and spatial stability metrics"],
            ui_appearance="Mode card with shared analysis settings and per-source segment selectors.",
            min_sources=1,
            supported_families=list(PRIMARY_FAMILIES),
            controls=base_controls,
        ),
        ModeSpec(
            id="point_to_point",
            label="Point to Point",
            tab="analysis",
            script_name="Frequency Analysis/Point to Point.py",
            purpose="Region/joint difference analysis over one or more sources.",
            required_inputs=["One or more selected sources"],
            optional_arguments=["hand", "fps", "wrist_joint_idx", "vertex_a", "vertex_b", "n_neighbors", "mediapipe_point_a", "mediapipe_point_b"],
            expected_outputs=["Magnitude trace", "PSD", "Dominant frequency", "Peak ratio", "Temporal and spatial stability metrics"],
            ui_appearance="Mode card with numeric controls for model vertices and MediaPipe joints.",
            min_sources=1,
            supported_families=list(PRIMARY_FAMILIES),
            controls=base_controls + [
                ControlSpec(id="vertex_a", label="Model Vertex A", type="number", required=True, default=4, min=0, max=777, step=1),
                ControlSpec(id="vertex_b", label="Model Vertex B", type="number", required=True, default=8, min=0, max=777, step=1),
                ControlSpec(id="n_neighbors", label="Region Neighbors", type="number", default=25, min=1, max=250, step=1),
                ControlSpec(id="mediapipe_point_a", label="MediaPipe Joint A", type="number", required=True, default=4, min=0, max=20, step=1),
                ControlSpec(id="mediapipe_point_b", label="MediaPipe Joint B", type="number", required=True, default=8, min=0, max=20, step=1),
            ],
        ),
        ModeSpec(
            id="multi_point",
            label="Multi Pair",
            tab="analysis",
            script_name="Frequency Analysis/Multi Point to Point.py",
            purpose="Multi-pair analysis across one or more selected sources.",
            required_inputs=["One or more selected sources"],
            optional_arguments=["hand", "fps", "wrist_joint_idx", "n_neighbors", "mano_pairs_text", "mediapipe_pairs_text"],
            expected_outputs=["Multi-pair magnitude plots", "PSD", "Dominant frequency", "Peak ratio", "Temporal and spatial stability metrics per pair"],
            ui_appearance="Mode card with comma-separated pair list controls.",
            min_sources=1,
            supported_families=list(PRIMARY_FAMILIES),
            controls=base_controls + [
                ControlSpec(id="n_neighbors", label="Region Neighbors", type="number", default=25, min=1, max=250, step=1),
                ControlSpec(id="mano_pairs_text", label="Model Pairs", type="text", placeholder="4-8, 9-13", help="Comma-separated vertex pairs."),
                ControlSpec(id="mediapipe_pairs_text", label="MediaPipe Pairs", type="text", placeholder="4-8, 8-12", help="Comma-separated joint pairs."),
            ],
        ),
        ModeSpec(
            id="neighbor_sweep",
            label="Neighbor Sweep",
            tab="analysis",
            script_name="Frequency Analysis/Point to Point Neighbor Sweep.py",
            purpose="Region-size sweep over one or more selected model sources.",
            required_inputs=["One or more model sources"],
            optional_arguments=["hand", "fps", "wrist_joint_idx", "vertex_a", "vertex_b", "point_counts_text"],
            expected_outputs=["Dominant frequency vs region size", "RMS vs region size"],
            ui_appearance="Mode card with vertex controls and comma-separated point counts.",
            min_sources=1,
            supported_families=["wilor", "wilor_finetune", "hamba", "dynhamr", "stride"],
            controls=base_controls + [
                ControlSpec(id="vertex_a", label="Model Vertex A", type="number", required=True, default=4, min=0, max=777, step=1),
                ControlSpec(id="vertex_b", label="Model Vertex B", type="number", required=True, default=8, min=0, max=777, step=1),
                ControlSpec(id="point_counts_text", label="Point Counts", type="text", default="10,20,30,40,50", placeholder="10,20,30,40,50"),
            ],
        ),
        ModeSpec(
            id="camera_space_frequency",
            label="Camera-Space Frequency",
            tab="analysis",
            script_name="Frequency Analysis/WiLoR Camera Space.py",
            purpose="Camera-space point-pair frequency analysis for a single compatible model source.",
            required_inputs=["Exactly one compatible model source"],
            optional_arguments=["hand", "fps", "wrist_joint_idx", "n_neighbors", "mano_pairs_text"],
            expected_outputs=["Magnitude trace", "PSD", "Dominant frequency", "Peak ratio", "Temporal and spatial stability metrics"],
            ui_appearance="Mode card with model-pair and neighbor controls.",
            min_sources=1,
            max_sources=1,
            supported_families=["wilor", "wilor_finetune", "dynhamr", "stride"],
            controls=base_controls + [
                ControlSpec(id="n_neighbors", label="Region Neighbors", type="number", default=25, min=1, max=250, step=1),
                ControlSpec(id="mano_pairs_text", label="Model Pairs", type="text", default="4-8", placeholder="4-8, 9-13"),
            ],
        ),
        ModeSpec(
            id="beta_comparison",
            label="Beta Comparison",
            tab="analysis",
            script_name="Frequency Analysis/beta comparison.py",
            purpose="Compare raw model output against a sequence-average-beta reconstruction for one source.",
            required_inputs=["Exactly one beta-compatible model source"],
            optional_arguments=["hand", "fps", "wrist_joint_idx", "vertex_a", "vertex_b", "n_neighbors"],
            expected_outputs=["Comparison traces", "PSD", "Dominant frequency", "Peak ratio", "Temporal and spatial stability metrics for raw and beta-average variants"],
            ui_appearance="Mode card with point-pair controls and one selected source.",
            min_sources=1,
            max_sources=1,
            supported_families=["wilor", "wilor_finetune", "dynhamr", "stride"],
            controls=base_controls + [
                ControlSpec(id="vertex_a", label="Model Vertex A", type="number", required=True, default=4, min=0, max=777, step=1),
                ControlSpec(id="vertex_b", label="Model Vertex B", type="number", required=True, default=8, min=0, max=777, step=1),
                ControlSpec(id="n_neighbors", label="Region Neighbors", type="number", default=25, min=1, max=250, step=1),
            ],
        ),
        ModeSpec(
            id="beta_multi_point",
            label="Beta Multi Pair",
            tab="analysis",
            script_name="Frequency Analysis/beta multi point to point.py",
            purpose="Multi-pair comparison between raw and sequence-average-beta reconstruction for one source.",
            required_inputs=["Exactly one beta-compatible model source"],
            optional_arguments=["hand", "fps", "wrist_joint_idx", "n_neighbors", "mano_pairs_text"],
            expected_outputs=["Multi-pair comparison traces", "PSD", "Dominant frequency", "Peak ratio", "Temporal and spatial stability metrics"],
            ui_appearance="Mode card with comma-separated model pair list.",
            min_sources=1,
            max_sources=1,
            supported_families=["wilor", "wilor_finetune", "dynhamr", "stride"],
            controls=base_controls + [
                ControlSpec(id="n_neighbors", label="Region Neighbors", type="number", default=25, min=1, max=250, step=1),
                ControlSpec(id="mano_pairs_text", label="Model Pairs", type="text", default="4-8, 9-13", placeholder="4-8, 9-13"),
            ],
        ),
    ]
